language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

before_install:
# install tiff
  - sudo apt-get update
#  - sudo apt-get -y purge ruby libtiff4 libtiff4-dev libtiffxx0c2 zlib1g-dev
#  - sudo apt-get autoremove
  - cat ./cpan-deps | cpanm --sudo --notest

install:
  - perl ./Build.PL --travis
  - ./Build
  - sudo ./Build install

script: prove -v

notifications:
  irc: irc.perl.org#sdl
